### ISSUE TITLE
Compilation error on CentOS 6.5

### ISSUE THREAD

**Issue by bmikhael** [wanproxy/wanproxy#7] opened 2016-03-10 02:31 UTC
I'm trying to compile the code from Github, I get the following error on CentOS 6.5 with g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)

g++ -I../.. -Wno-deprecated -Wnon-virtual-dtor -include common/common.h -pipe -O -g -W -Wall -Wno-system-headers -Wno-uninitialized -Wpointer-arith -Wreturn-type -Wcast-qual -Wwrite-strings -Wswitch -Wshadow -Wcast-align -Wunused-parameter -Wchar-subscripts -Wreorder -DTHREADS -c -o time.o ../../common/time/time.cc
g++ -I../.. -Wno-deprecated -Wnon-virtual-dtor -include common/common.h -pipe -O -g -W -Wall -Wno-system-headers -Wno-uninitialized -Wpointer-arith -Wreturn-type -Wcast-qual -Wwrite-strings -Wswitch -Wshadow -Wcast-align -Wunused-parameter -Wchar-subscripts -Wreorder -DTHREADS -c -o uuid_libuuid.o ../../common/uuid/uuid_libuuid.cc
../../common/uuid/uuid_libuuid.cc:26:23: error: uuid/uuid.h: No such file or directory
In file included from ../../common/uuid/uuid_libuuid.cc:28:
../../common/buffer.h: In member function ‘BufferSegment* BufferSegment::unshare()’:
../../common/buffer.h:316: warning: declaration of ‘data’ shadows a member of 'this'
../../common/uuid/uuid_libuuid.cc: In member function ‘bool UUID::decode(Buffer*)’:
../../common/uuid/uuid_libuuid.cc:41: error: ‘uuid_t’ was not declared in this scope
../../common/uuid/uuid_libuuid.cc:41: error: expected ‘;’ before ‘uuid’
../../common/uuid/uuid_libuuid.cc:42: error: ‘uuid’ was not declared in this scope
../../common/uuid/uuid_libuuid.cc:42: error: ‘uuid_parse’ was not declared in this scope
../../common/uuid/uuid_libuuid.cc: In member function ‘void UUID::generate()’:
../../common/uuid/uuid_libuuid.cc:53: error: ‘uuid_t’ was not declared in this scope
../../common/uuid/uuid_libuuid.cc:53: error: expected ‘;’ before ‘uuid’
../../common/uuid/uuid_libuuid.cc:57: error: ‘uuid’ was not declared in this scope
../../common/uuid/uuid_libuuid.cc:57: error: ‘uuid_generate’ was not declared in this scope
../../common/uuid/uuid_libuuid.cc:58: error: ‘uuid_unparse’ was not declared in this scope
make: *** [uuid_libuuid.o] Error 1

**Comment by caladri** [comment] 2016-03-10 02:35
Duplicate of #8; issue is the same even if different versions of CentOS are involved.

**Closed by caladri** 2016-03-10 02:35 UTC
