### ISSUE TITLE
Unable to compile WanProxy on Debian 10

### ISSUE THREAD

**Issue by dtouzeau** [wanproxy/wanproxy#23] opened 2019-09-23 12:33 UTC
Here the make error on a debian 10 amd64
How can i fix it ?

```
make[1] : on entre dans le répertoire « /root/wanproxy/programs/diskdup »
g++ -I../.. -Wno-deprecated -Wnon-virtual-dtor -include common/common.h -pipe -O -g -W -Wall -Wno-system-headers -Wno-uninitialized -Wpointer-arith -Wreturn-type -Wcast-qual -Wwrite-strings -Wswitch -Wshadow -Wcast-align -Wunused-parameter -Wchar-subscripts -Wreorder -DTHREADS -c -o diskdup.o diskdup.cc
diskdup.cc: In member function ‘void DiskDup::read_complete(Event, bool)’:
diskdup.cc:97:11: error: ‘struct Event’ has no member named ‘buffer_’
    if (!e.buffer_.empty()) {
           ^~~~~~~
diskdup.cc:112:23: error: ‘struct Event’ has no member named ‘buffer_’
    target_buffer_ = e.buffer_;
                       ^~~~~~~
diskdup.cc:116:23: error: ‘struct Event’ has no member named ‘buffer_’
    source_buffer_ = e.buffer_;
                       ^~~~~~~
diskdup.cc: In member function ‘void DiskDup::schedule_close()’:
diskdup.cc:168:25: error: ‘callback’ was not declared in this scope
   SimpleCallback *scb = callback(this, &DiskDup::close_complete, false);
                         ^~~~~~~~
diskdup.cc:168:25: note: suggested alternative: ‘calloc’
   SimpleCallback *scb = callback(this, &DiskDup::close_complete, false);
                         ^~~~~~~~
                         calloc
diskdup.cc: In member function ‘void DiskDup::schedule_read()’:
diskdup.cc:181:24: error: ‘callback’ was not declared in this scope
   EventCallback *scb = callback(this, &DiskDup::read_complete, false);
                        ^~~~~~~~
diskdup.cc:181:24: note: suggested alternative: ‘calloc’
   EventCallback *scb = callback(this, &DiskDup::read_complete, false);
                        ^~~~~~~~
                        calloc
diskdup.cc:182:52: error: no matching function for call to ‘BlockHandle::read(uint64_t&, EventCallback*&)’
   source_action_ = source_->read(block_number_, scb);
                                                    ^
In file included from diskdup.cc:33:
../../io/block_handle.h:40:18: note: candidate: ‘virtual Action* BlockHandle::read(off_t, BufferEventCallback*)’
  virtual Action *read(off_t, BufferEventCallback *);
                  ^~~~
../../io/block_handle.h:40:18: note:   no known conversion for argument 2 from ‘EventCallback*’ {aka ‘TypedCallback<Event>*’} to ‘BufferEventCallback*’ {aka ‘TypedPairCallback<Event, Buffer>*’}
diskdup.cc:186:52: error: no matching function for call to ‘BlockHandle::read(uint64_t&, EventCallback*&)’
   target_action_ = target_->read(block_number_, tcb);
                                                    ^
In file included from diskdup.cc:33:
../../io/block_handle.h:40:18: note: candidate: ‘virtual Action* BlockHandle::read(off_t, BufferEventCallback*)’
  virtual Action *read(off_t, BufferEventCallback *);
                  ^~~~
../../io/block_handle.h:40:18: note:   no known conversion for argument 2 from ‘EventCallback*’ {aka ‘TypedCallback<Event>*’} to ‘BufferEventCallback*’ {aka ‘TypedPairCallback<Event, Buffer>*’}
diskdup.cc: In member function ‘void DiskDup::schedule_write()’:
diskdup.cc:193:23: error: ‘callback’ was not declared in this scope
   EventCallback *cb = callback(this, &DiskDup::write_complete);
                       ^~~~~~~~
diskdup.cc:193:23: note: suggested alternative: ‘calloc’
   EventCallback *cb = callback(this, &DiskDup::write_complete);
                       ^~~~~~~~
                       calloc
make[1]: *** [../../common/program.mk:128: diskdup.o] Error 1
make[1] : on quitte le répertoire « /root/wanproxy/programs/diskdup »
make: *** [../common/subdir.mk:2: all] Error 2
```

**Comment by caladri** [comment] 2019-09-23 13:23
Build in `/programs/wanproxy`, and not in the top-level directory.  Duplicate of #3 by @dtouzeau.

**Closed as completed by caladri** 2019-09-23 13:23 UTC
